apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-portal.fullname" . }}
  namespace: dev-portal
  labels:
    app: {{ include "dev-portal.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "dev-portal.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
