apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-dev-portal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/georg-nikola/dev-portal
    targetRevision: HEAD
    path: helm/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-portal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
