apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-portal
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=ghcr.io/georg-nikola/dev-portal
    argocd-image-updater.argoproj.io/frontend.update-strategy: semver
    argocd-image-updater.argoproj.io/frontend.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: image.tag
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/georg-nikola/dev-portal
    targetRevision: HEAD
    path: helm/dev-portal
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-portal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
